version: '3.3'
services:
    mongodb:
        container_name: mongodb
        image: 'mongodb:latest'

    takagi:
        container_name: takagi
        ports:
            - '127.0.0.1:5000:8000'
        environment:
            - MONGO_ADDRESS=mongodb
        image: 'rangerdigital/takagi:latest'
        depends_on:
        - mongodb
