version: '3.3'
services:
    mongo:
        container_name: takagi_prod_mongo
        image: 'mongo:latest'
        volumes:
        - takagi_prod_data:/data/db
        deploy:
          restart_policy:
            condition: always

    redis:
        container_name: takagi_prod_redis
        image: 'redis:latest'
        deploy:
          restart_policy:
            condition: always

    takagi:
        container_name: takagi
        ports:
            - '127.0.0.1:7979:8000'
        environment:
            - MONGO_ADDRESS=takagi_prod_mongo
            - REDIS_ADDRESS=takagi_prod_redis
            - JWT_SECRET_KEY=
        image: 'rangerdigital/takagi:latest'
        deploy:
          restart_policy:
            condition: always
        depends_on:
        - mongo
        - redis

volumes:
  takagi_prod_data:
