version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/frontend"
    target_branch: "master"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_name: "*"
          update_type: "all"

  - package_manager: "python"
    directory: "/backend"
    target_branch: "master"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_name: "*"
          update_type: "all"
